### ISSUE TITLE
DATETIME_FORMAT causes issues with samba on Windows

### ISSUE THREAD

**Issue by mynameisdaniel32** [robmarkcole/HASS-Deepstack-object#123]
I updated to 3.1 last night and am finding that since then, all jpegs saved now have cryptic names instead of the timestamps. They are the correct/same boxes with the boxes. Examples below:
![image](https://user-images.githubusercontent.com/24840952/81995989-0b27ce00-968b-11ea-89e6-7bf998d5c704.png)
Before:
![image](https://user-images.githubusercontent.com/24840952/81996006-167af980-968b-11ea-8ad7-e4ca9f4d17cd.png)

**Comment by robmarkcole** [comment]
those might be temporary files? looks like you are on windows, and I do not have a windows machine to debug on I am afraid

**Comment by unbornx** [comment]
Happened to me.
I'll explain what I did.

I access those files through windows smb share to my docker files.
Those files are mangled files 8.3 from samba because the file contains colon, ex :deepstack_object_cam2_person_2020-05-18_07:12:37.jpg
The actual file is ok in linux, but displayed strangely to windows.
I activated mangled names=no to my smb.conf so it displays the file, but still can't acess it because windows does not allow colon in file names.
I ended up modifying image_processing.py to dashes instead of colons, ex : DATETIME_FORMAT = "%Y-%m-%d_%H-%M-%S"
Now it works.

**Comment by robmarkcole** [comment]
Well glad you managed to get to the bottom of it. Im tempter to implement the DATETIME_FORMAT you suggest, although that will no doubt upset other people who have created automations etc. Will keep this open to take the temperature of how common this issue is

**Comment by Justahobby01** [comment]
I would certainly welcome the change since samba is much easier to use than HA's file editor when trying to reference images.

**Comment by robmarkcole** [comment]
fixed in v3.2
