### ISSUE TITLE
[Feature request] Multiple snapshots scan on motion

### ISSUE THREAD

**Issue by koldogut** [robmarkcole/HASS-Deepstack-object#150]
Quite often the motion sensor triggers the image processing when someone is not in the best position to be recognized and as motion keeps on, the object recognition automation finish and it's not triggered again. This causes missed people gettin in/out events, moreover at night as cameras infrared snapshots are sometimes blurry. The idea is to take several snapshots while movement is ON and report the highest score match per 1,2 or 5 secconds.

I'll try to achieve this via automation but it will be great to have it already as a feature.

**Comment by Cavekeeper** [comment]
@koldogut I'm also looking for a solution here. I have multiple cameras. If a trigger arrives several times, there is also an error message in the log. It should actually work if you add a condition to the automation. How did you solve that temporarily?

**Comment by koldogut** [comment]
With this automation; it calls the image_processing service every second while motion sensor is on.  

```
repeat:
  until:
    - condition: template
      value_template: '{{ not is_state(''trigger.entity_id'', ''on'') }}'
  sequence:
    - service: image_processing.scan
      data_template:
        entity_id: |
          {% if trigger.entity_id == 'binary_sensor.motion_entrada' %}
            image_processing.deepstack_object_entrada
          {% elif trigger.entity_id == 'binary_sensor.motion_jardin' %}
            image_processing.deepstack_object_jardin
          {% elif trigger.entity_id == 'binary_sensor.motion_garaje' %}
            image_processing.deepstack_object_garaje
          {% elif trigger.entity_id == 'binary_sensor.motion_pta_principal' %}
            image_processing.deepstack_object_pta_principal
          {% elif trigger.entity_id == 'binary_sensor.motion_sotano' %}
            image_processing.deepstack_object_sotano
          {% elif trigger.entity_id == 'binary_sensor.motion_terraza' %}
            image_processing.deepstack_object_terraza
          {% elif trigger.entity_id == 'binary_sensor.motion_cocina' %}
            image_processing.deepstack_object_cocina
          {% endif %}
    - delay: '00:00:01'
```
This way you don't miss any event but my problem now is it always keep people at the end of their path as latest_image. I've enabled save_timestamped_file to true and I'm working on an automation to create an mp4 with ffmpeg to attach a video with all the snapshots in the notification, the shell_command is more or less like this (still under testing)

`shell_command:
  extract_motion: 'cat /config/snapshots/"{{deep_stack_cam}}"*.jpg | ffmpeg -f image2pipe -r 3 -vcodec mjpeg -i - -vcodec libx264  /config/snapshots/"{{deep_stack_cam}}".mp4'`

**Comment by Cavekeeper** [comment]
@koldogut Thank you for the good description. I am in the same situation. At least two cameras can trigger simultaneously and trigger the image_processing.scan service. I also need a condition for this. But now I get the triggers via a webhook. These would then have to be built into a condition. I'm not getting anywhere at the moment. I would not like to set up additional binary switches as helpers for this. What do you think?

**Comment by koldogut** [comment]
I don't know if I'm understanding you well, but If you capture the webhooks via events, these can be the triggers for your automation. With the Option restart on your automation there shouldn't be overlappings as image processing for first camera stops  when the second one fires the event.

**Comment by robmarkcole** [comment]
This would be a feature on image_processing in home assistant

**Comment by jodur** [comment]
I have about te same problem with this component. The flaw of this component is that it is designed to use a still image for object detection. Don't understand me wrong, i love the work that has been done. In order to get a reliable object detection for moving objects, you have to process multiple frames (when you capture a frame with  a lot of motion, it might be to blurry for objectdetection). There are also serveral things to consider when using this component:

1 The (motion) signal that is used to start a objectdetection
2 The delay in the camera stream feed in home assistant

When point 1 and point 2 are not on the same timeframe (in ohter words out of sync, for example i have a 4 sec delay in the stream that is showed in home assistant) you probally wil miss the object that you want to detect when using 1 frame (asuming that this delay is also in the image capture proces within image processing routine.)

I am using a NVIDEA Jeston for Deepstack, and did some testing with processing the direct rtsp camera streams in python on my laptop and there i see no flaws because it is processing several frames in order (Also with deepstack using your deepstack.core component). In case of motion you see that that some frames are missed/not recognized, because they are blurry, but that is no problem because a next frame will be recognized. This is for me the eye-opener ,that you have to use a stream or several frames in order to get a reliable detection.

When looking at a other solution (for example [frigate)](https://github.com/blakeblackshear/frigate) , where i have no experience with, is using a stream (direct rtsp streams (no camera entities, this will resolve the delay issue))

I am not able yet to get a reliable objectdetection with this component, but i would love to. What are your experience with it and suggestions are welcome?  I used 2 camera's for object detection, with a repeat in the automation to capture a "burst of frames" after motion detection, but i still miss detections and is not reliable yet. I have to debug further is the component is able to start scans simulatanous and independtly. (The image_processing is fully async, so that will not be the problem?)

**Comment by koldogut** [comment]
This is the problem I had a month ago and I solved this with the automation posted above on Nov 13th 
[https://github.com/robmarkcole/HASS-Deepstack-object/issues/150#issuecomment-726859235](url)

Basically it starts processing snapshots every second of motion (you can set the delay even to milliseconds), this way I ensure people is recognized at least in one of them; results: No more missed events since then. However, motion is triggered by my cameras almost instantly -vía Unifi Protect integration- and may be others with longer delays and short time-window to record motion (ie, alleys) where this solution might be not enough. Processing the rstp stream could be indeed less resources dependant and gets better results.

**Comment by robmarkcole** [comment]
@koldogut can you provide the automation?
For a full on CCTV solution with motion tracking and integrating Deepstack for object detection I see people have been using BlueIris. We are going to document this on the Deepstack docs soon, or you can follow the [link from the Deepstack repo](https://github.com/johnolafenwa/DeepStack)

**Comment by koldogut** [comment]
Here you are full automation code, I ended up setting the automation to be working in parallel as it's also for face detection in one of the cameras:

`
alias: Seguridad - Procesamiento de imágenes
description: ''
trigger:
  - entity_id: binary_sensor.motion_1
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_2
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_3
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_4
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_5
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_6
    platform: state
    to: 'on'
  - platform: state
    entity_id: binary_sensor.motion_7
    to: 'on'
condition: []
action:
  - repeat:
      until:
        - condition: template
          value_template: '{{ is_state(trigger.entity_id, ''off'') }}'
      sequence:
        - service: image_processing.scan
          data_template:
            entity_id: >
              {% if trigger.entity_id == 'binary_sensor.motion_1' %}
                image_processing.deepstack_object_1
              {% elif trigger.entity_id == 'binary_sensor.motion_2' %}
                image_processing.deepstack_object_2
              {% elif trigger.entity_id == 'binary_sensor.motion_3' %}
                image_processing.deepstack_object_3
              {% elif trigger.entity_id == 'binary_sensor.motion_4'
              %}
                image_processing.deepstack_object_4
              {% elif trigger.entity_id == 'binary_sensor.motion_5' %}
                image_processing.deepstack_object_5
              {% elif trigger.entity_id == 'binary_sensor.motion_6' %}
                image_processing.deepstack_object_6
              {% elif trigger.entity_id == 'binary_sensor.motion_7' %}
                image_processing.face_counter_7
              {% endif %}
        - delay: '00:00:01'
mode: parallel
max: 20`

**Comment by koldogut** [comment]
> @koldogut can you provide the automation?
> For a full on CCTV solution with motion tracking and integrating Deepstack for object detection I see people have been using BlueIris. We are going to document this on the Deepstack docs soon, or you can follow the [link from the Deepstack repo](https://github.com/johnolafenwa/DeepStack)

Blue Iris is a great solution for non-unifi cameras, I gave it a try following this video [https://youtu.be/fwoonl5JKgo](url) and works great.

**Comment by jodur** [comment]
I am aware that this exist in blue-iris, but then you need a powerfull pc/server for this purpose. I'am convinced that a working solution would be possible on a Rassperry Pi 4 device in combination with a low-cost Jetson Nano only running deepstack. I have about the same solution as you provied above, only i have seperate automations per camera. I didn't say it was not working, but in my case not 100% reliabale yet.  @koldogut I like you idea of creating a MP4 afterwards, how succesfull have you been and are you willing to share some expierence and code? After creating a MP4 you have to delete the grabbed frames and it would be nice if we could show the latest grabbed frame also in a camera entity.

**Comment by robmarkcole** [comment]
I have just enabled Discussions on this repo, can we move the conversation there as I want to keep Issues for code issues. Thanks!
